"""empty message

Revision ID: 547c98338d50
Revises: b185273a6ed7
Create Date: 2024-07-26 09:51:20.362528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547c98338d50'
down_revision = 'b185273a6ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_discount_id_fkey', type_='foreignkey')
        batch_op.drop_column('discount_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('product_discount_id_fkey', 'discount', ['discount_id'], ['id'])

    # ### end Alembic commands ###
