"""empty message

Revision ID: 690a49eca2ef
Revises: ff06e678f1f2
Create Date: 2024-07-25 00:08:15.240769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690a49eca2ef'
down_revision = 'ff06e678f1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('discount_value', sa.Float(), nullable=False))
        batch_op.drop_constraint('coupon_discount_id_fkey', type_='foreignkey')
        batch_op.drop_column('discount_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('coupon_discount_id_fkey', 'discount', ['discount_id'], ['id'])
        batch_op.drop_column('discount_value')
        batch_op.drop_column('discount_type')

    # ### end Alembic commands ###
